---
title: "Fallen eggs"
description: " "
order: 8
---

We have a building with `100 floors and 2 eggs.` What is the optimal strategy in order to `find the floor where the eggs break` by minimizing the worst case scenario ?

::: {.callout-tip collapse="true"}
## 💡 Hint (1)

If we try the floor n for the first drop and it breaks then the worst case scenario for the second is to try every floor from 1 to n-1, so the total number of drops would be n.
:::

::: {.callout-tip collapse="true"}
## 💡 Hint (2)

If we try the floor n for the first drop and it does not break and then we try the floor 2n and it breaks then the worst case scenario for the second egg is to try every floor from n+1 to 2n-1, so the total number of drops would be n+1. So we need a strategy where for each successful drop of the first egg, we reduce by one unit the worst-case scenario for the second one. 
:::

::: {.callout-tip collapse="true"}
## 💡 Solution

Naively, if we try a drop at the floor 50 (100/2) and it breaks then in the worst-case scenario we have to try all floors from 1 to 49 so we would need 49 drops for the second egg (in that case, the floor where the egg starts to break is either 49 or 50). So the worst-case scenario would be $WC_{\text{half}} = 1 + 49 = 50 \; \text{drops}.$

The idea is that if the egg breaks at 50 then we don't have enough information, thus let's try the floor 10 and add 10 each time. If the egg breaks at 50 (5 drops of the first egg to get there), then in the worst-case scenario we have to try all floors from 41 to 49 so we would need 9 additional drops. Accordingly, $WC_{\text{constant}} = 5 + 9 = 14 < WC_{\text{half}}.$ We already have a better strategy than the first one. However, if instead of breaking at 50, the first egg breaks at 90, we would still need to test 9 values in the worst-case scenario (81, ..., 89). So the total number of drops will raise to 18. Therefore, `we need a strategy where every successful drop of the first egg, leeds to a smaller uncertainty of the second egg by one unit.`

This optimal strategy would be that at the first drop we try the floor $n$. If it does not succeed then in the worst scenario, we would add n-1 drops (1,2, ..., n-1) so the total amount would be n. If the first drop is a success then we try the floor $n + (n-1) = 2n-1$. If this one does not succeed then in the worst scenario, we would add n-2 drops (n+1, ..., 2n-2) so the total will remain n. Accordingly, we need to find n such that $n + (n-1) + (n-2) + ... + 1\ge100$ (the sum needs to end at 1 because let's say we are at 97 and we try 99 and it fails we don't know if it breaks at 98 or 99). The condition is the same as $n(n+1)\ge200.$ By testing, a few values we find $\boxed{n_{\text{optimal}} = 14.}$

`Therefore, we are trying the floors 14, 27, 39, 50, 60, 69, 77, 84, 90, 95, 99 and the number of total drops in the worst-case scenario is always 14.`