<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mihnea POPA">
<meta name="dcterms.date" content="2026-06-01">

<title>Optimal Execution for a $10M AAPL Buy Order   (AI-Assisted) – Mihnea POPA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
p {
  text-align: justify;
  text-justify: inter-word;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Mihnea POPA</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> <i class="bi bi-person-circle" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> <i class="bi bi-file-earmark-check" role="img">
</i> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../quant_research.html"> <i class="bi bi-bar-chart-line" role="img">
</i> 
<span class="menu-text">Quantitative Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../socio_economic_research.html"> <i class="bi bi-people" role="img">
</i> 
<span class="menu-text">Socio-Economic Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../teaching.html"> <i class="bi bi-mortarboard" role="img">
</i> 
<span class="menu-text">Teaching</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-benchmark-twap-12" id="toc-the-benchmark-twap-12" class="nav-link active" data-scroll-target="#the-benchmark-twap-12">The benchmark: TWAP-12</a></li>
  <li><a href="#v1-segment-voting-momentum-with-ifelif-branching" id="toc-v1-segment-voting-momentum-with-ifelif-branching" class="nav-link" data-scroll-target="#v1-segment-voting-momentum-with-ifelif-branching">V1: segment-voting momentum with if/elif branching</a></li>
  <li><a href="#v2-a-unified-urgency-score" id="toc-v2-a-unified-urgency-score" class="nav-link" data-scroll-target="#v2-a-unified-urgency-score">V2: a unified urgency score</a></li>
  <li><a href="#hidden-date-results-a-genuine-trade-off-not-a-clean-win" id="toc-hidden-date-results-a-genuine-trade-off-not-a-clean-win" class="nav-link" data-scroll-target="#hidden-date-results-a-genuine-trade-off-not-a-clean-win">Hidden-date results: a genuine trade-off, not a clean win</a></li>
  <li><a href="#limits" id="toc-limits" class="nav-link" data-scroll-target="#limits">Limits</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Optimal Execution for a $10M AAPL Buy Order <br> (AI-Assisted)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mihnea POPA </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This page documents the executor assignment from <strong>MGMTMFE 412: Trading, Market Frictions, and FinTech</strong> at UCLA Anderson: build an algorithm that buys $10,000,000 of <code>AAPL</code> between 14:30 and 20:00 UTC, minimizing implementation shortfall (IS) relative to the arrival mid-price, and have it graded against a TWAP-12 starter strategy on hidden out-of-sample dates. As with the trader pages, every version of the code was developed together with <strong>Claude (Anthropic)</strong>: I supplied the assignment brief, the previous version’s code, and the instructor’s feedback, and Claude proposed and implemented the execution logic, which I then tested locally and submitted. All figures below come from the autograder’s <code>summary.json</code> / <code>twap_comparison.csv</code> outputs and the instructor’s feedback reports.</p>
<section id="the-benchmark-twap-12" class="level3">
<h3 class="anchored" data-anchor-id="the-benchmark-twap-12">The benchmark: TWAP-12</h3>
<p>The starter strategy slices the order into 12 equal market orders spread evenly across the 5.5-hour window. On the training date (2024-05-21) it completes 99.98% of the order (52,022 of a 52,022-share target) at an average fill price of $192.3749, for an implementation shortfall of <strong>7.80 bps / $7,799.55</strong>. Beating this benchmark — not in absolute terms, but in the <code>skill_bps = student_SF - TWAP_SF</code> sense defined by the grader — is the entire game.</p>
</section>
<section id="v1-segment-voting-momentum-with-ifelif-branching" class="level3">
<h3 class="anchored" data-anchor-id="v1-segment-voting-momentum-with-ifelif-branching">V1: segment-voting momentum with if/elif branching</h3>
<p>V1 is a 5-minute clock-bucket executor. At each checkpoint it computes a <em>segment-voting momentum</em> signal — the 15-minute lookback is split into three independent 5-minute sub-windows, each compared against a smoothed mid-price anchor, and a trade direction is confirmed only if at least 2 of 3 sub-windows agree (with a <code>min_valid_segments=3</code> guard to avoid false signals in the first 15 minutes). This vote is combined with an L1 book-imbalance multiplier and a spread-aware limit/market order selector, on top of a geometric-decay base schedule (<code>remaining_qty × dynamic_frac</code>) that naturally front-loads execution.</p>
<p>On the training date this scored <strong>1.80 bps</strong> — a huge improvement over TWAP’s 7.80 bps, since front-loading is exactly the right thing to do on an uptrend day (buy before the price rises further). But the decision logic was a stack of hard-coded <code>if/elif</code> branches with discrete multipliers (2x / 1.3x / 0.6x), which the instructor’s feedback flagged as the strategy’s central weakness: “what is missing is the guide’s unified urgency score… the student uses separate if/elif branches… rather than a single linear combination that allows all signals to interact continuously.”</p>
<p>Before committing to V1’s signal set, I ran an empirical accuracy comparison of L1 vs.&nbsp;L2 directional signals on the training date, at both 1-minute and 5-minute horizons:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Signal</th>
<th>1-min accuracy</th>
<th>5-min accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>L1 static imbalance</td>
<td>47.5%</td>
<td><strong>55.4%</strong></td>
</tr>
<tr class="even">
<td>L2 static imbalance (10 levels)</td>
<td>34.4%</td>
<td>44.9%</td>
</tr>
<tr class="odd">
<td>L2 depth-weighted microprice</td>
<td>32.8%</td>
<td>45.3%</td>
</tr>
<tr class="even">
<td>Multi-level order-flow imbalance (Cont et al., 2014)</td>
<td><strong>47.7%</strong></td>
<td>—</td>
</tr>
</tbody>
</table>
<p>L2 signals were <em>worse than random</em> at the 5-minute checkpoint horizon for AAPL — the instructor’s read is that “HFT market-maker quoting dominates levels 1-9,” so depth beyond the top of book is mostly noise for a 5-minute decision cadence. That result is why both V1 and V2 stayed L1-only by design.</p>
<p>Two alternatives were tried and rejected before settling on the geometric-decay + signal-multiplier design. A pure VWAP-tracking schedule gave <strong>9.70 bps</strong> — <em>worse</em> than TWAP, because on an uptrend day VWAP “back-loads into peak prices.” A fixed-fraction schedule (<code>BASE_FRACTION=0.07</code> applied uniformly, no signals at all) gave <strong>1.05 bps</strong> — the best in-sample number of any variant — but was rejected as overfit to a single uptrend training day with no adaptive mechanism for a different regime.</p>
</section>
<section id="v2-a-unified-urgency-score" class="level3">
<h3 class="anchored" data-anchor-id="v2-a-unified-urgency-score">V2: a unified urgency score</h3>
<p>The redesign replaced the if/elif tree with a single continuous urgency score combining five normalized signals:</p>
<p><span class="math display">\[
u_t = 0.40\,\text{deficit}_{\text{norm}} + 0.25\,\text{drift}_{\text{norm}} + 0.20\,\text{imb}_{\text{norm}} + 0.15\,\text{time}_{\text{norm}}^2 - 0.10\,\text{spread}_{\text{norm}}
\]</span></p>
<p><span class="math display">\[
\text{multiplier} = \text{clip}(1 + u_t,\ 0.30,\ 2.50), \qquad \text{qty\_slice} = \left\lfloor \text{remaining} \times \text{BASE\_FRACTION} \times \text{multiplier} \right\rfloor
\]</span></p>
<p>The key design choice — and the explicit fix for V1’s failure mode — is that <code>BETA_DEFICIT = 0.40</code> is set to <em>dominate</em> the combined bearish contribution (<code>BETA_DRIFT + BETA_IMB = 0.45</code>, but at moderate signal levels <code>0.40</code> alone still outweighs the realistic combined drag), so schedule-catch-up pressure can no longer be fully overridden by a bearish drift + imbalance read the way V1’s <code>if/elif</code> chain allowed. The full parameter set:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>CHECK_INTERVAL_SECONDS</code></td>
<td>300</td>
<td><code>BETA_DEFICIT</code></td>
<td>0.40</td>
</tr>
<tr class="even">
<td><code>BASE_FRACTION</code></td>
<td>0.06</td>
<td><code>BETA_DRIFT</code></td>
<td>0.25</td>
</tr>
<tr class="odd">
<td><code>TREND_LOOKBACK_SEC</code></td>
<td>900</td>
<td><code>BETA_IMB</code></td>
<td>0.20</td>
</tr>
<tr class="even">
<td><code>TREND_THRESHOLD_BPS</code></td>
<td>1.0</td>
<td><code>BETA_TIME</code></td>
<td>0.15</td>
</tr>
<tr class="odd">
<td><code>min_valid_segments</code></td>
<td>3</td>
<td><code>BETA_SPREAD</code></td>
<td>0.10</td>
</tr>
<tr class="even">
<td><code>IMB_THRESHOLD</code></td>
<td>0.05</td>
<td><code>URGENCY_MULT_MIN</code></td>
<td>0.30</td>
</tr>
<tr class="odd">
<td><code>COMPLETION_WINDOW_FRAC</code></td>
<td>0.20</td>
<td><code>URGENCY_MULT_MAX</code></td>
<td>2.50</td>
</tr>
<tr class="even">
<td><code>SPREAD_LIMIT_THRESHOLD_BPS</code></td>
<td>0.80</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><code>TIME_LIMIT_MAX_FRAC</code></td>
<td>0.65</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>On the training date, V2 scores <strong>2.36 bps</strong> in the current local evaluation (2.46 bps was the figure during development, before minor post-write-up tuning) — <em>slightly worse</em> than V1’s 1.80 bps. That in-sample regression was accepted deliberately, on the bet that a continuous, principled urgency score would generalize better than a brittle if/elif tree.</p>
<p><img src="is_progression.png" class="img-fluid" style="width:100.0%"></p>
</section>
<section id="hidden-date-results-a-genuine-trade-off-not-a-clean-win" class="level3">
<h3 class="anchored" data-anchor-id="hidden-date-results-a-genuine-trade-off-not-a-clean-win">Hidden-date results: a genuine trade-off, not a clean win</h3>
<p>The grader’s <code>skill_bps = student_SF - TWAP_SF</code>, with the convention that <strong>negative skill means the student beat TWAP</strong> and positive skill means TWAP won. Reading the two hidden dates with that sign convention in mind:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Hidden date (weight)</th>
<th>TWAP SF</th>
<th>V1 student SF</th>
<th>V1 skill</th>
<th>V2 student SF</th>
<th>V2 skill</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2025-10-30 (60%)</td>
<td>81.87 bps</td>
<td>49.78 bps</td>
<td>-32.09 bps</td>
<td>35.37 bps</td>
<td><strong>-46.50 bps</strong></td>
</tr>
<tr class="even">
<td>2025-04-08 (40%, crash)</td>
<td>-516.84 bps</td>
<td>-251.93 bps</td>
<td>+264.91 bps</td>
<td>-158.27 bps</td>
<td>+358.57 bps</td>
</tr>
<tr class="odd">
<td><strong>Weighted</strong></td>
<td>—</td>
<td>—</td>
<td><strong>+86.71 bps</strong></td>
<td>—</td>
<td><strong>+115.53 bps</strong></td>
</tr>
</tbody>
</table>
<p><img src="hidden_skill_comparison.png" class="img-fluid" style="width:100.0%"></p>
<p>V2 <em>did</em> improve on the calm/up day (2025-10-30): it beat TWAP by 46.50 bps versus V1’s 32.09 bps. But on the actual crash day in the hidden set (2025-04-08), V2 underperformed TWAP by 358.57 bps — <em>more</em> than V1’s 264.91 bps underperformance. Both versions lose to TWAP on this date because TWAP’s even pacing keeps buying all the way to the close, capturing more of a day-long price decline than either front-loaded strategy; V2’s <code>BETA_DEFICIT</code>-dominance fix, by design, keeps it closer to its front-loaded base schedule even when the drift signal turns bearish, so it ends up <em>more</em> front-loaded than V1 on this date — and therefore captures even less of the decline. Because the crash day carries 40% of the weight, the net weighted skill got slightly <em>worse</em> (+86.71 → +115.53, where larger positive numbers mean “loses to TWAP by more”), and the instructor’s final grade moved from <strong>96.0/100 (V1) to 93.2/100 (V2)</strong>. “No lookahead detected” held for both submissions.</p>
<p>The pacing chart below — built from the current code’s actual fill timestamps on the training date — shows just how front-loaded V2 is in practice: it reaches roughly 90% completion within about two hours of the 14:30 arrival, versus TWAP’s even 12-slice pacing across the full 5.5-hour window.</p>
<p><img src="execution_curve.png" class="img-fluid" style="width:100.0%"></p>
</section>
<section id="limits" class="level3">
<h3 class="anchored" data-anchor-id="limits">Limits</h3>
<p>The headline result here is not “V2 beat V1” — on the hidden dates it didn’t, and the grade reflects that. What V2 <em>did</em> do is replace a brittle architecture (hard-coded if/elif branches that the instructor identified as a structural risk) with a principled, continuous formulation whose failure mode is at least legible: it is structurally biased toward front-loading, which is correct on trending-up days and on the 2025-10-30 hidden date, but costly on the one genuine crash day in the hidden set. Two concrete gaps remain, both flagged directly in the feedback. First, the drift component is still a hand-crafted segment-voting heuristic, not the regression-based signal the course guide specifies — fitting <span class="math inline">\(r_{t,t+h} = a + b_1 \cdot \text{imbalance} + b_2 \cdot \text{microprice\_gap} + b_3 \cdot \text{recent\_return}\)</span> on a rolling window of past observations would replace the hard-coded 1.0 bps threshold with data-driven coefficients and add a microprice-gap signal that’s currently absent entirely. Second, the urgency score has no depth-cost term: with <span class="math inline">\(u_t\)</span> missing a <span class="math inline">\(-\beta_5 \cdot \text{depth\_cost}\)</span> component, the strategy never slows down when the best ask is thin, even though an L1-only proxy (<code>qty_this_slice / ask_sz_00</code>, capped to a 10-20% participation rate) would be straightforward to add. Either change would also give the strategy a principled way to <em>reduce</em> front-loading specifically when the order book signals it’s expensive to do so — which is precisely the lever that’s missing from the current trade-off between the two hidden dates.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>