project:
  type: website
  output-dir: docs 

website:
  title: "Mihnea POPA"
  navbar:
    left:
      - href: index.qmd
        text: About
        icon: person-circle
      - href: resume.qmd
        text: Resume
        icon: file-earmark-check
      - href: quant_research.qmd  
        text: Quantitative Research
        icon: bar-chart-line
      - href: socio_economic_research.qmd
        text: Socio-Economic Research
        icon: people
      - href: teaching.qmd  
        text: Teaching 
        icon: mortarboard
        
  search: false
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



