<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mihnea POPA">
<meta name="dcterms.date" content="2026-06-01">

<title>Adaptive Inventory-Aware Market Making on SOFI — AI-Assisted Development – Mihnea POPA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
p {
  text-align: justify;
  text-justify: inter-word;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Mihnea POPA</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> <i class="bi bi-person-circle" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> <i class="bi bi-file-earmark-check" role="img">
</i> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../quant_research.html"> <i class="bi bi-bar-chart-line" role="img">
</i> 
<span class="menu-text">Quantitative Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../socio_economic_research.html"> <i class="bi bi-people" role="img">
</i> 
<span class="menu-text">Socio-Economic Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../teaching.html"> <i class="bi bi-mortarboard" role="img">
</i> 
<span class="menu-text">Teaching</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#week-7-baseline-a-avellaneda-stoikov-quoter-and-where-it-breaks" id="toc-week-7-baseline-a-avellaneda-stoikov-quoter-and-where-it-breaks" class="nav-link active" data-scroll-target="#week-7-baseline-a-avellaneda-stoikov-quoter-and-where-it-breaks">Week 7 baseline: a Avellaneda-Stoikov quoter, and where it breaks</a></li>
  <li><a href="#week-8-six-targeted-fixes" id="toc-week-8-six-targeted-fixes" class="nav-link" data-scroll-target="#week-8-six-targeted-fixes">Week 8: six targeted fixes</a></li>
  <li><a href="#local-self-evaluation-development-day-2024-08-01" id="toc-local-self-evaluation-development-day-2024-08-01" class="nav-link" data-scroll-target="#local-self-evaluation-development-day-2024-08-01">Local self-evaluation (development day, 2024-08-01)</a></li>
  <li><a href="#hidden-date-results-week-7-vs-week-8" id="toc-hidden-date-results-week-7-vs-week-8" class="nav-link" data-scroll-target="#hidden-date-results-week-7-vs-week-8">Hidden-date results: Week 7 vs Week 8</a></li>
  <li><a href="#limits" id="toc-limits" class="nav-link" data-scroll-target="#limits">Limits</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Adaptive Inventory-Aware Market Making on SOFI — AI-Assisted Development</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mihnea POPA </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This page documents the market-making assignment from <strong>MGMTMFE 412: Trading, Market Frictions, and FinTech</strong> at UCLA Anderson: maintain a two-sided quote on <code>SOFI</code> using a callback API (<code>build_strategy</code> → <code>on_market_event</code> / <code>on_fill</code>) against full L3 order-book data, graded on three hidden out-of-sample dates by</p>
<p><span class="math display">\[
\text{Score}
= \text{NetPnL}
- 0.20\,\overline{\lvert q \rvert}
- 50\,(0.30 - \text{two-sided ratio})^{+}
- 10\,\text{market orders}
- 25\,\text{violations}.
\]</span></p>
<p>As with the other strategies, the code was developed iteratively with <strong>Claude (Anthropic)</strong>: I supplied the assignment brief, the previous week’s code, and the instructor’s feedback, and Claude proposed and implemented the quoting logic, which I then tested locally before submission. All figures below come from the autograder’s <code>summary.json</code> outputs and the instructor’s feedback reports.</p>
<section id="week-7-baseline-a-avellaneda-stoikov-quoter-and-where-it-breaks" class="level3">
<h3 class="anchored" data-anchor-id="week-7-baseline-a-avellaneda-stoikov-quoter-and-where-it-breaks">Week 7 baseline: a Avellaneda-Stoikov quoter, and where it breaks</h3>
<p>The week-7 submission implements a linear inventory-skewed reservation price, <span class="math inline">\(r = \text{mid} - 0.10 \cdot q \cdot \text{tick}\)</span>, quoting 10 shares on each side with a 1-tick half-spread. Its main engineering contribution is a <em>safe-cancel</em> guard — only cancel an order that is provably behind the NBBO (a resting sell above the current ask, or a resting buy below the current bid) — combined with a two-level throttle: Level 1 immediately resubmits only the side that just got filled, while Level 2 refreshes both sides every 150 events. An inventory taper linearly reduces the accumulating side’s size as <span class="math inline">\(|q|\)</span> grows from 150 to 300 shares.</p>
<p>On the hidden dates this scored an aggregate <strong>-301.9</strong>, with net PnL of <strong>-$180.02</strong>, a two-sided quote coverage of only 0.45 (below the 0.30 penalty threshold is fine, but barely), and <strong>1 violation</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Date</th>
<th>PnL</th>
<th>Drawdown</th>
<th>Score</th>
<th>Fills</th>
<th>Violations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2024-12-26</td>
<td>$58.68</td>
<td>-$35.09</td>
<td>24.72</td>
<td>126</td>
<td>0</td>
</tr>
<tr class="even">
<td>2025-04-08</td>
<td>$59.27</td>
<td>-$161.22</td>
<td>22.33</td>
<td>291</td>
<td>0</td>
</tr>
<tr class="odd">
<td>2025-08-26</td>
<td>-$297.98</td>
<td>-$307.52</td>
<td>-348.94</td>
<td>857</td>
<td>1</td>
</tr>
<tr class="even">
<td><strong>Aggregate</strong></td>
<td><strong>-$180.02</strong></td>
<td><strong>-$307.52</strong></td>
<td><strong>-301.9</strong></td>
<td>—</td>
<td><strong>1</strong></td>
</tr>
</tbody>
</table>
<p>The first two dates were fine; 2025-08-26 was a collapse, single-handedly producing nearly all of the aggregate loss and the only violation. The instructor’s review traced this to three compounding issues: the safe-cancel guard prevents <em>race</em> violations but doesn’t address <em>adverse selection</em> — the actual driver of the 2025-08-26 loss; the linear skew term is effectively cosmetic because the inventory taper clamps the position near <span class="math inline">\(|q|=20\)</span> shares, well before the skew can meaningfully lean the quotes; and the fixed 150-event throttle is blind to the NBBO, so it can both refresh needlessly on a flat market and fail to react quickly enough during a fast move. The review also noted the strategy implements the <em>core</em> AS framework (reservation price, inventory skew, throttle, tapering) but is missing a microprice/OFI signal tilt (it quotes around the simple mid), implied-alpha calibration (<code>SKEW_K=0.10</code> is hand-picked), endgame flatten logic, and any markout-based toxicity filter — an Innovation score of 78/100 (Framework 19, Signal Quality 17, Originality 22, Implementation 20).</p>
</section>
<section id="week-8-six-targeted-fixes" class="level3">
<h3 class="anchored" data-anchor-id="week-8-six-targeted-fixes">Week 8: six targeted fixes</h3>
<p>Rather than a rewrite, week 8 kept the AS skeleton and layered on six changes aimed squarely at the three diagnosed weaknesses:</p>
<ol type="1">
<li><strong>Move-gate throttle</strong> — the Level-2 refresh now fires only when both 150 events have passed <em>and</em> the NBBO has moved by at least one tick, eliminating churn on flat markets while staying responsive to price moves.</li>
<li><strong>Stronger, non-cosmetic skew</strong> — a regime-dependent <code>extra_skew</code> adds up to 2 ticks (Warning regime: a fraction of 2 ticks; Critical regime: a flat 2 ticks) on top of the linear <code>SKEW_K</code> term, and the inventory clamp that previously bound at <span class="math inline">\(|q|=20\)</span> was raised from 2 to 4 ticks.</li>
<li><strong>Multi-regime inventory guard</strong> — Normal (<span class="math inline">\(|q|\le180\)</span>), Warning (<span class="math inline">\(180&lt;|q|\le250\)</span>), and Critical (<span class="math inline">\(|q|&gt;250\)</span>, hard cap at <code>MAX_INVENTORY=300</code>) each get distinct tapering and quote-sending logic, rather than one linear taper across the whole range.</li>
<li><strong>Microprice reference</strong> — the reservation price is now anchored to a queue-weighted microprice, <span class="math inline">\(\text{microprice} = \frac{P_{\text{ask}} \cdot Q_{\text{bid}} + P_{\text{bid}} \cdot Q_{\text{ask}}}{Q_{\text{bid}} + Q_{\text{ask}}}\)</span>, rather than the simple mid — systematically reducing adverse selection.</li>
<li><strong>Endgame flatten</strong> — in the final 7% of the session, the skew multiplier jumps to <span class="math inline">\(4\times\)</span>, aggressively pushing the strategy back toward a flat position before the close.</li>
<li><strong>Fill-rate monitor + directional fill signal</strong> — a 300-event rolling window that widens both sides by 1 tick if 3+ fills occur in the window (a trending-regime detector), plus a <em>directional</em> signal: if 3+ consecutive fills land on the same side, that side’s quote is pushed back by 1 tick — asymmetrically, so the unwinding side stays competitive. The instructor’s review called this “the single most effective adverse-selection defense in the submission.”</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Value</th>
<th>Parameter</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>QUOTE_SIZE</code></td>
<td>5</td>
<td><code>FILL_RATE_WINDOW</code></td>
<td>300</td>
</tr>
<tr class="even">
<td><code>SOFT_INVENTORY</code></td>
<td>80</td>
<td><code>FILL_RATE_THRESH</code></td>
<td>3</td>
</tr>
<tr class="odd">
<td><code>NORMAL_INV</code></td>
<td>180</td>
<td><code>VOL_EXTRA_TICKS</code></td>
<td>1</td>
</tr>
<tr class="even">
<td><code>CRITICAL_INV</code></td>
<td>250</td>
<td><code>ENDGAME_PCT</code></td>
<td>0.07</td>
</tr>
<tr class="odd">
<td><code>MAX_INVENTORY</code></td>
<td>300</td>
<td><code>ENDGAME_SKEW_MULT</code></td>
<td>4.0</td>
</tr>
<tr class="even">
<td><code>SKEW_K</code></td>
<td>0.10</td>
<td><code>DIRECTIONAL_THRESH</code></td>
<td>3</td>
</tr>
<tr class="odd">
<td><code>EXTRA_SKEW_TICKS</code></td>
<td>2</td>
<td><code>DIRECTIONAL_TICKS</code></td>
<td>1</td>
</tr>
<tr class="even">
<td><code>MIN_EVENTS_BETWEEN_REFRESH</code></td>
<td>150</td>
<td><code>CANCEL_TICKS</code></td>
<td>2</td>
</tr>
</tbody>
</table>
<p>A separate change worth calling out on its own: halving <code>QUOTE_SIZE</code> from 10 to 5 shares was, by itself, the single highest-leverage tweak across both weeks, since it directly halves the per-fill adverse-selection exposure that drives the inventory swings on volatile days. One idea that was tried and <em>rejected</em>: posting one tick behind the touch (to reduce fill probability on the wrong side) made things worse on the local self-evaluation day, taking the score from -17.76 to -59.26 — fewer, more lopsided fills hurt more than they helped.</p>
</section>
<section id="local-self-evaluation-development-day-2024-08-01" class="level3">
<h3 class="anchored" data-anchor-id="local-self-evaluation-development-day-2024-08-01">Local self-evaluation (development day, 2024-08-01)</h3>
<p>On the development day used for local iteration, the final week-8 strategy posted a net PnL of <strong>-$1.42</strong>, max drawdown -$3.25, 350 fills across 473 orders, a maker fill ratio of 0.91 (320 maker / 29 taker fills), a mean two-sided quote ratio of 0.73, and <strong>zero violations</strong>, for a self-eval score of <strong>-3.36</strong>. The score decomposition is informative: <span class="math inline">\(-3.36 = (-1.42) - 0.50|q_{\text{end}}| - 0.20\,\overline{|q|}\)</span>, with the end-of-day inventory term at zero (the strategy finished flat) and the mean-absolute-inventory penalty contributing the remaining -1.94 — i.e., on this particular day, the strategy’s PnL was nearly break-even and the score was dominated by the cost of simply <em>carrying</em> inventory throughout the session, not by any blow-up.</p>
<p><img src="pnl_curve.png" class="img-fluid" style="width:100.0%"></p>
<p><img src="inventory_path.png" class="img-fluid" style="width:100.0%"></p>
<p>The inventory path stayed within roughly ±25-30 shares all day — comfortably inside the ±80 soft-taper threshold and nowhere near the Warning (180) or Critical (250) regime boundaries. That’s a useful sanity check on the <em>mechanics</em> (safe-cancel, move-gate, microprice reference all functioning with zero violations), but it also means <strong>this particular development day never stress-tested the multi-regime guard, the endgame flatten, or the directional fill signal</strong> — those three features only matter on the kind of high-fill-rate, trending day that 2025-08-26 turned out to be in the hidden set.</p>
</section>
<section id="hidden-date-results-week-7-vs-week-8" class="level3">
<h3 class="anchored" data-anchor-id="hidden-date-results-week-7-vs-week-8">Hidden-date results: Week 7 vs Week 8</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Date</th>
<th>W7 PnL</th>
<th>W8 PnL</th>
<th>ΔPnL</th>
<th>W7 Score</th>
<th>W8 Score</th>
<th>ΔScore</th>
<th>Violations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2024-12-26</td>
<td>$58.68</td>
<td>$46.09</td>
<td>-$12.59</td>
<td>24.72</td>
<td>24.84</td>
<td>+0.12</td>
<td>0 → 0</td>
</tr>
<tr class="even">
<td>2025-04-08</td>
<td>$59.27</td>
<td>$54.19</td>
<td>-$5.08</td>
<td>22.33</td>
<td>32.91</td>
<td>+10.59</td>
<td>0 → 0</td>
</tr>
<tr class="odd">
<td>2025-08-26</td>
<td>-$297.98</td>
<td>-$85.79</td>
<td>+$212.18</td>
<td>-348.94</td>
<td>-102.59</td>
<td>+246.35</td>
<td>1 → 0</td>
</tr>
<tr class="even">
<td><strong>Weighted</strong></td>
<td><strong>-$180.02</strong></td>
<td><strong>$14.48</strong></td>
<td><strong>+$194.50</strong></td>
<td><strong>-301.9</strong></td>
<td><strong>-44.83</strong></td>
<td><strong>+257.07</strong></td>
<td><strong>1 → 0</strong></td>
</tr>
</tbody>
</table>
<p><img src="comparison.png" class="img-fluid" style="width:100.0%"></p>
<p>The pattern is exactly the trade-off you’d hope for from a <em>risk-control</em> iteration: on the two calm days, week 8 gives up a little PnL (-$12.59 and -$5.08) — the price of carrying a tighter regime guard and a slightly wider directional-signal quote — while on the volatile day (2025-08-26), the directional fill signal fired early and often during a trending regime with 800 fills, cutting the loss from -$297.98 to -$85.79 and eliminating the violation entirely. Net effect: aggregate PnL flips from -$180.02 to <strong>+$14.48</strong>, and the aggregate score improves by +257 points (-301.9 → -44.83). The instructor’s review marked this “Clear improvement vs Week 7” and raised the Innovation score from 78/100 to <strong>99/100</strong> (Framework 25, Signal Quality 24, Originality 25, Implementation 25), with 58.2% code similarity to week 7 — i.e., a targeted iteration, not a rewrite.</p>
</section>
<section id="limits" class="level3">
<h3 class="anchored" data-anchor-id="limits">Limits</h3>
<p>The honest summary is: <strong>week 8 turned a catastrophic day into a merely bad one, not a good one.</strong> 2025-08-26 still loses -$85.79 and is still the single worst day by a wide margin — the directional fill signal helps, but <code>DIRECTIONAL_TICKS=1</code> may simply be too small a pushback for a market trending 5+ ticks in one direction, and the Critical regime’s response is to pull one side of the quote entirely, causing temporary one-sided dropout that drags the two-sided ratio down to 0.52 (above the 0.30 penalty threshold, but with little room left). The fill-rate monitor also widens <em>both</em> sides symmetrically when the trending-regime trigger fires, which reduces spread capture on the side that’s actually helping the strategy unwind — an avoidable cost. And the aggregate score, while dramatically improved, is still <strong>negative</strong> (-44.83): this is a strategy that has gotten much less bad, not one that is profitable on a risk-adjusted basis across the hidden set.</p>
<p>The instructor’s suggestions for a further iteration are concrete and worth recording here as the natural next steps: add a markout-based toxicity diagnostic — an EWMA of <span class="math inline">\(-\text{sign}(\text{fill side})\times(\text{mid}_{t+1s} - \text{fill price})\)</span> — and <em>pause</em> quoting for 10-20 events when it crosses a threshold, rather than only widening; scale <code>DIRECTIONAL_TICKS</code> adaptively (2 ticks at 5+ consecutive same-side fills, pull the accumulating side entirely for 50 events at 7+); make the fill-rate widening asymmetric (apply it only to the side that’s been filling); add hysteresis to the Critical-regime side-pull (restore the pulled side once <span class="math inline">\(|q|\)</span> drops back below 240, rather than waiting to fully exit Critical); and finally, implement the implied-alpha calibration suggested back in week 7 — fitting <code>SKEW_K</code> from observed NBBO spreads via an inverted AS formula, rather than hand-picking 0.10 — which has now been an open suggestion across both rounds of feedback.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>