<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mihnea Popa">
<meta name="dcterms.date" content="2024-08-01">

<title>Standard Unit Cost Benchmarks for Prison Vocational Training – Mihnea POPA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
p {
  text-align: justify;
  text-justify: inter-word;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Mihnea POPA</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> <i class="bi bi-person-circle" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> <i class="bi bi-file-earmark-check" role="img">
</i> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../quant_research.html"> <i class="bi bi-bar-chart-line" role="img">
</i> 
<span class="menu-text">Quantitative Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../socio_economic_research.html"> <i class="bi bi-people" role="img">
</i> 
<span class="menu-text">Socio-Economic Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../teaching.html"> <i class="bi bi-mortarboard" role="img">
</i> 
<span class="menu-text">Teaching</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#why-this-matters-european-funds-and-the-audit-problem" id="toc-why-this-matters-european-funds-and-the-audit-problem" class="nav-link active" data-scroll-target="#why-this-matters-european-funds-and-the-audit-problem">Why This Matters: European Funds and the Audit Problem</a></li>
  <li><a href="#the-prison-vocational-training-program" id="toc-the-prison-vocational-training-program" class="nav-link" data-scroll-target="#the-prison-vocational-training-program">The Prison Vocational Training Program</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#step-1-identifying-the-relevant-variables" id="toc-step-1-identifying-the-relevant-variables" class="nav-link" data-scroll-target="#step-1-identifying-the-relevant-variables">Step 1 — Identifying the Relevant Variables</a></li>
  <li><a href="#step-2-building-the-groups-with-cart" id="toc-step-2-building-the-groups-with-cart" class="nav-link" data-scroll-target="#step-2-building-the-groups-with-cart">Step 2 — Building the Groups with CART</a></li>
  <li><a href="#step-3-measuring-the-estimation-error" id="toc-step-3-measuring-the-estimation-error" class="nav-link" data-scroll-target="#step-3-measuring-the-estimation-error">Step 3 — Measuring the Estimation Error</a></li>
  <li><a href="#broader-context" id="toc-broader-context" class="nav-link" data-scroll-target="#broader-context">Broader Context</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Standard Unit Cost Benchmarks for Prison Vocational Training</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mihnea Popa </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 1, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This page presents the main technical work from my internship at the <strong>Direction des Politiques Européennes (DPE)</strong> of the <strong>Conseil Régional des Pays de la Loire</strong>, in Nantes, from June to September 2024. The mission was to build a statistical pricing grid — a <em>Barème Standard de Coûts Unitaires</em> (BSCU) — for the vocational training programs organized inside the six prisons of the Pays de la Loire region.</p>
<section id="why-this-matters-european-funds-and-the-audit-problem" class="level3">
<h3 class="anchored" data-anchor-id="why-this-matters-european-funds-and-the-audit-problem">Why This Matters: European Funds and the Audit Problem</h3>
<p>The European Union co-finances regional development projects through several funds. In Pays de la Loire, the 2021–2027 European program mobilises <strong>625 million euros</strong>, of which 64.5M€ comes from the <strong>European Social Fund (FSE+)</strong>. The FSE+ focuses on employment, training, and social inclusion.</p>
<p>When public money is spent on a project — say, a training program for prisoners — the spending authority must prove to the European Commission that every euro was justified. In practice, this means auditors check every invoice, every timesheet, and every attendance record for every trainee in every training session. For a region managing dozens of training contracts across six prison facilities over multiple years, this is an enormous administrative burden.</p>
<p>The EU allows a way out through <strong>Simplified Cost Options (Options de Coûts Simplifiés, OCS)</strong>. Instead of verifying each actual expense, the region can pre-agree on a standard flat rate per trainee and per type of training. Once that rate is validated by the European Commission, reimbursement becomes automatic: if 20 trainees completed a welding program at Nantes, the region gets reimbursed <span class="math inline">\(20 \times \text{rate}\)</span> without needing to justify each individual hour. This makes audits dramatically faster and more reliable. Building such a rate table from historical data is exactly what a BSCU does.</p>
</section>
<section id="the-prison-vocational-training-program" class="level3">
<h3 class="anchored" data-anchor-id="the-prison-vocational-training-program">The Prison Vocational Training Program</h3>
<p>Since the <strong>Law of 5 March 2014</strong>, French regions are responsible for funding and organising vocational training inside public penitentiary establishments. The rationale is straightforward: giving prisoners a certified trade or skill during their sentence significantly improves their chances of finding employment after release — which in turn reduces recidivism. Training therefore serves a dual purpose: it provides individual social mobility and generates a broader public safety benefit.</p>
<p>The Pays de la Loire region funds training in six facilities:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Facility</th>
<th>City</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Centre de détention</td>
<td>Nantes</td>
<td>Long sentences (CD)</td>
</tr>
<tr class="even">
<td>Maison d’arrêt</td>
<td>Angers</td>
<td>Remand / Short sentences</td>
</tr>
<tr class="odd">
<td>Maison d’arrêt</td>
<td>Le Mans</td>
<td>Remand / Short sentences</td>
</tr>
<tr class="even">
<td>Maison d’arrêt</td>
<td>Laval</td>
<td>Remand / Short sentences</td>
</tr>
<tr class="odd">
<td>Maison d’arrêt</td>
<td>La Roche-sur-Yon / Fontenay-le-Comte</td>
<td>Remand / Short sentences</td>
</tr>
<tr class="even">
<td>Régional (CACES)</td>
<td>All sites</td>
<td>Forklift certification, multi-site</td>
</tr>
</tbody>
</table>
<p>This program falls under <strong>EU priority 4 “A more social region”</strong>, specific objective ESO4.7: <em>promoting lifelong learning and flexible upskilling</em>. Because the FSE+ co-finances these training sessions, the BSCU would replace expensive per-receipt audits with a simple per-trainee flat rate, saving significant administrative time on both the regional and European sides.</p>
</section>
<section id="the-data" class="level3">
<h3 class="anchored" data-anchor-id="the-data">The Data</h3>
<p>The dataset covers <strong>148 training actions</strong> carried out from 2019 to 2024 across the six facilities, representing <strong>2,891 trainees</strong> and a total expenditure of approximately <strong>6.7 million euros</strong>. Each row in the data is one training action (a contract between the region and a training provider for a specific type of program at a specific facility in a given year). The key variables are:</p>
<ul>
<li><strong><code>Centre_final</code></strong>: which of the six facilities hosted the training</li>
<li><strong><code>code_gfe</code></strong>: a letter code classifying the type of training (the <em>Groupe Formation Emploi</em>, or GFE — agriculture, construction, metalwork, transport, etc.)</li>
<li><strong><code>nb_stag</code></strong>: number of trainees who attended</li>
<li><strong><code>cout_tot</code></strong>: total cost of the action (in euros)</li>
<li><strong><code>prix_h</code></strong> and <strong><code>nb_h</code></strong>: hourly rate and number of hours (from which the total cost is derived)</li>
</ul>
<p>The target variable is the <strong>cost per trainee</strong>, computed as total cost divided by number of trainees. To make costs comparable across years, all amounts are normalised to a <strong>2022 base</strong> using the Syntec price index published by INSEE (which tracks price changes in the training services sector): 2021 values are deflated by a factor of 275/277.5, and all other years by 287.9/277.5.</p>
<p>The cost distribution by facility is quite spread out, reflecting real structural differences between centers:</p>
<p><img src="boxplot_centre.png" class="img-fluid" style="width:100.0%"></p>
<p>Nantes stands out with the highest median cost per trainee. This makes economic sense: the Nantes detention center runs longer, full-certification programs (300–700 hours leading to a <em>Titre Professionnel</em>) with more qualified instructors, whereas remand prisons like Laval or La Roche run shorter modules for a more transient population. The regional CACES forklift program has very low per-trainee costs because a single session serves trainees from multiple facilities at once, spreading fixed costs across many participants.</p>
</section>
<section id="step-1-identifying-the-relevant-variables" class="level3">
<h3 class="anchored" data-anchor-id="step-1-identifying-the-relevant-variables">Step 1 — Identifying the Relevant Variables</h3>
<p>The first question is: what actually drives the cost per trainee? An ordinary least squares (OLS) linear regression of the cost per trainee on all available variables — facility, year, number of trainees, total cost, hourly rate, hours, training provider, and training type (code GFE) — gives a first picture of which factors matter.</p>
<p>The regression reveals that the most informative predictors are the <strong>facility</strong> (<code>Centre_final</code>), the <strong>training type</strong> (<code>code_gfe</code>), and the <strong>training provider</strong> (<code>org_form</code>). A weighted OLS using just <code>Centre_final</code> and <code>code_gfe</code> already explains <strong>R² = 0.584</strong> of the variance in cost per trainee, meaning these two variables alone account for about 58% of the cost differences across training actions. Adding the provider improves fit further but at the cost of practical usability, since auditors would then need to verify the provider identity for each reimbursement — partially defeating the simplification goal.</p>
<p>A <strong>Fisher test</strong> on the facility variable confirms that the differences in average costs between the six centers are statistically significant and not random noise: the between-group variance is large relative to the within-group variance, so the facility genuinely matters for predicting the cost.</p>
</section>
<section id="step-2-building-the-groups-with-cart" class="level3">
<h3 class="anchored" data-anchor-id="step-2-building-the-groups-with-cart">Step 2 — Building the Groups with CART</h3>
<p>Once the key variables are identified, the next question is: what is the best way to group the possible (facility × training type) combinations into a small number of groups, each with a single flat rate? A CART model (<strong>Classification and Regression Trees</strong>) does exactly this.</p>
<p>CART is a decision-tree algorithm that recursively splits the data into groups to minimise a cost function — here, the weighted sum of squared differences between the actual cost per trainee and the group mean. The weights are the number of trainees, so a training action with 30 participants counts 30 times more than one with a single trainee.</p>
<p>The full tree is first grown to its maximum complexity, then <strong>pruned</strong> using a cost-complexity parameter: branches that contribute only a tiny improvement in fit are removed. The result is a tree with <strong>8 distinct price groups</strong>, which balances statistical precision with practical simplicity.</p>
<p>The pruned decision tree is shown below. The first split separates <strong>Nantes</strong> from the five other facilities: its cost structure is sufficiently different that the algorithm immediately sets it apart. Within the non-Nantes branch, a second split on training type distinguishes short, high-turnover modules (H, K, O, T) from longer, more skills-intensive programs (D, E, S, X). Within the Nantes branch, a split on training type separates low-cost insertion and hygiene programs (T, X) from the full technical certifications. The final refinements isolate <strong>Le Mans</strong> as its own sub-group: its per-trainee costs for both the H/K/O/T cluster and the X (insertion) cluster are noticeably different from the other <em>maisons d’arrêt</em>, reflecting differences in training provider contracts specific to that facility.</p>
<p><img src="tree_plot.png" class="img-fluid" style="width:100.0%"></p>
<p>The 8 groups and their estimated cost per trainee (in 2022 euros) are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Group</th>
<th>Facilities</th>
<th>Training types</th>
<th>Estimated cost / trainee (€, 2022 base)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Angers, La Roche/Fontenay, Laval, Région</td>
<td>Catering (K), Electricity (H), Transport (O), Hygiene (T)</td>
<td>693 €</td>
</tr>
<tr class="even">
<td>2</td>
<td>Le Mans</td>
<td>Insertion training (X)</td>
<td>1,253 €</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Nantes</td>
<td>Hygiene &amp; Security (T), Insertion training (X)</td>
<td>1,502 €</td>
</tr>
<tr class="even">
<td>4</td>
<td>Le Mans</td>
<td>Hygiene &amp; Security (T)</td>
<td>1,554 €</td>
</tr>
<tr class="odd">
<td>5</td>
<td>La Roche/Fontenay</td>
<td>Insertion training (X)</td>
<td>2,076 €</td>
</tr>
<tr class="even">
<td>6</td>
<td>Angers, Laval, Le Mans</td>
<td>Construction (D), Metal (E), Services (S)</td>
<td>2,491 €</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Nantes</td>
<td>Construction (D), Transport &amp; Logistics (O)</td>
<td>3,614 €</td>
</tr>
<tr class="even">
<td>8</td>
<td>Nantes</td>
<td>Agriculture (A), Metal (E), Electricity (H)</td>
<td>4,484 €</td>
</tr>
</tbody>
</table>
<p>The same result visualised by group:</p>
<p><img src="bscu_barchart.png" class="img-fluid" style="width:100.0%"></p>
<p>Several patterns are worth noting. <strong>Nantes consistently costs more</strong> for technical trades: the facility operates full-length professional certification programs (often 600+ hours) with highly qualified instructors, whereas remand prisons run shorter modules for a more transient population. <strong>Insertion and hygiene training (T and X) are cheap</strong> across all centers because these programs are short, high-density sessions with minimal per-trainee equipment cost — though even here, Nantes’s structured format (1,502€) costs roughly twice what the same type of training costs at the other maisons d’arrêt (693€ for H/K/O/T programs). The <strong>Le Mans anomaly</strong> is one of the more interesting findings: for insertion training (X), Le Mans is the cheapest non-Nantes center at 1,253€, while La Roche/Fontenay runs the same type of training at 2,076€ — a factor of nearly 1.7. For hygiene training (T), Le Mans is conversely the most expensive maison d’arrêt at 1,554€ versus 693€ at the other centers. Both effects point to provider-specific contract structures at Le Mans rather than any structural difference in what trainees need.</p>
</section>
<section id="step-3-measuring-the-estimation-error" class="level3">
<h3 class="anchored" data-anchor-id="step-3-measuring-the-estimation-error">Step 3 — Measuring the Estimation Error</h3>
<p>A BSCU is only useful if it is reasonably accurate. The total actual expenditure across all 148 training actions is <strong>6,719,644 €</strong>. The BSCU with 8 groups estimates <strong>6,735,390 €</strong>, a global difference of <strong>+15,746 € (+0.23%)</strong>. This near-perfect aggregate accuracy — a 0.23% over-estimation — is a significant improvement over a coarser segmentation, and demonstrates that the eight-group grid captures the true cost structure of the program with high fidelity.</p>
<p>The scatter plot below compares actual and estimated costs action by action (each point is one training action; point size reflects the number of trainees):</p>
<p><img src="actual_vs_estimated.png" class="img-fluid" style="width:100.0%"></p>
<p>Most points sit close to the red dashed line of perfect estimation. The main sources of error are a handful of actions with unusually small or large cohorts in 2024, where the per-trainee cost deviates significantly from the group average — exactly the kind of outlier that a flat-rate system is not designed to handle but that is acceptable for the purposes of EU reimbursement, as long as the global error over a program period remains low. The 8-group model reduces the estimation variance relative to a coarser segmentation, in particular by isolating Le Mans and by splitting Nantes’s technical programs into two sub-groups (D/O versus A/E/H).</p>
</section>
<section id="broader-context" class="level3">
<h3 class="anchored" data-anchor-id="broader-context">Broader Context</h3>
<p>This work sits at the intersection of <strong>public economics</strong> and <strong>social policy</strong>. From a public finance perspective, the BSCU is a tool for reducing transaction costs in a principal-agent relationship: the European Commission (principal) cannot directly observe how regional funds are spent in each prison, and verifying every invoice is expensive. A pre-validated flat rate changes the contract structure — it shifts the risk of under- or over-spending from the EU to the region, but in exchange removes the verification burden. This is a well-studied mechanism in the economics of public contracts and is broadly similar to prospective payment systems used in healthcare (e.g., DRGs in French hospitals).</p>
<p>From a <strong>social science</strong> perspective, the variation in costs across facilities reflects deeper structural inequalities in the prison system. The Centre de détention in Nantes, which holds long-sentence inmates, can offer sustained, accrediting programs and invest in qualified instructors precisely because the population is stable enough to complete a 600-hour program. Remand prisons face constant turnover, shorter stays, and less predictable enrollment — which constrains what kind of training is feasible and pushes providers toward shorter, cheaper modules. The BSCU, by pricing these differences into a grid of 8 groups, implicitly acknowledges that meaningful vocational training for prisoners serving longer sentences genuinely costs more — and that the European co-financing system should fund that difference rather than penalise it through uniform pricing. The fact that Le Mans emerges as its own sub-group within the maisons d’arrêt is a further reminder that even within the same institutional category, procurement history and provider relationships create cost structures that a single flat rate would obscure.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>