<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mihnea POPA et al.">
<meta name="dcterms.date" content="2026-05-01">

<title>Graph Neural Network Features for Dynamic S&amp;P 500 Portfolio Construction – Mihnea POPA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
p {
  text-align: justify;
  text-justify: inter-word;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Mihnea POPA</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> <i class="bi bi-person-circle" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> <i class="bi bi-file-earmark-check" role="img">
</i> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../quant_research.html"> <i class="bi bi-bar-chart-line" role="img">
</i> 
<span class="menu-text">Quantitative Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../socio_economic_research.html"> <i class="bi bi-people" role="img">
</i> 
<span class="menu-text">Socio-Economic Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../teaching.html"> <i class="bi bi-mortarboard" role="img">
</i> 
<span class="menu-text">Teaching</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#data-and-dynamic-graph-construction" id="toc-data-and-dynamic-graph-construction" class="nav-link active" data-scroll-target="#data-and-dynamic-graph-construction">Data and dynamic graph construction</a></li>
  <li><a href="#gnn-message-passing-models" id="toc-gnn-message-passing-models" class="nav-link" data-scroll-target="#gnn-message-passing-models">GNN message-passing models</a></li>
  <li><a href="#walk-forward-backtest-protocol" id="toc-walk-forward-backtest-protocol" class="nav-link" data-scroll-target="#walk-forward-backtest-protocol">Walk-forward backtest protocol</a></li>
  <li><a href="#stage-1-direct-gnn-portfolio-models" id="toc-stage-1-direct-gnn-portfolio-models" class="nav-link" data-scroll-target="#stage-1-direct-gnn-portfolio-models">Stage 1: direct GNN portfolio models</a></li>
  <li><a href="#stage-2-gcn-as-a-feature-extractor-for-random-forest" id="toc-stage-2-gcn-as-a-feature-extractor-for-random-forest" class="nav-link" data-scroll-target="#stage-2-gcn-as-a-feature-extractor-for-random-forest">Stage 2: GCN as a feature extractor for Random Forest</a></li>
  <li><a href="#stage-3-frozen-rf-gcn-final-strategy" id="toc-stage-3-frozen-rf-gcn-final-strategy" class="nav-link" data-scroll-target="#stage-3-frozen-rf-gcn-final-strategy">Stage 3: frozen RF + GCN final strategy</a></li>
  <li><a href="#limits" id="toc-limits" class="nav-link" data-scroll-target="#limits">Limits</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Graph Neural Network Features for Dynamic S&amp;P 500 Portfolio Construction</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mihnea POPA et al. </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This page presents a group project from the <strong>Machine Learning and Data Analytics</strong> course at UCLA Anderson. The central question is whether graph neural networks can improve portfolio construction on a dynamic S&amp;P 500 universe. The data come from WRDS/CRSP daily stock files and historical S&amp;P 500 membership records, covering 1,110 distinct PERMNOs over 4,788,231 daily rows. The investable universe is rebuilt every month from <em>active</em> index constituents (499–506 stocks per month), so the study mitigates the survivor-only bias that would arise from selecting today’s index members and backfilling them through history. The out-of-sample period runs from 2015-01-30 to 2024-11-29, spanning 119 monthly rebalances — enough for a meaningful but still single-path evaluation.</p>
<p>The research design unfolds in three stages. Stage 1 asks whether a GNN score alone can rank stocks well enough to build a competitive portfolio. Stage 2 changes the role of the GNN: rather than a direct portfolio model, the GCN is used as a graph-aware feature extractor whose outputs are fed into a Random Forest rank model. Stage 3 freezes the best configuration found in Stage 2 — before OOS evaluation, with no annual model switching — and reports the final result.</p>
<p>The headline OOS numbers (119 monthly rebalances, 10 bps transaction cost per unit of turnover) are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Strategy</th>
<th>Ann. Return</th>
<th>Ann. Vol.</th>
<th>Sharpe</th>
<th>Max DD</th>
<th>Turnover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RF + GCN Final</td>
<td>12.33%</td>
<td>18.24%</td>
<td>0.676</td>
<td>-24.99%</td>
<td>1.60</td>
</tr>
<tr class="even">
<td>RF Base</td>
<td>10.44%</td>
<td>18.28%</td>
<td>0.571</td>
<td>-29.25%</td>
<td>1.71</td>
</tr>
<tr class="odd">
<td>EqualWeight</td>
<td>10.66%</td>
<td>18.06%</td>
<td>0.590</td>
<td>-31.48%</td>
<td>0.02</td>
</tr>
<tr class="even">
<td>Momentum60</td>
<td>5.50%</td>
<td>20.14%</td>
<td>0.273</td>
<td>-34.10%</td>
<td>1.29</td>
</tr>
</tbody>
</table>
<p>The main conclusion is not that GNNs universally beat tabular models. It is more specific: <em>direct</em> GNN portfolios are mixed and do not consistently dominate EqualWeight, but GCN <em>representations</em> — a scalar score plus a 64-dimensional embedding per stock — add useful relational information to a conventional RF model, improving Sharpe and maximum drawdown relative to RF Base, EqualWeight, and Momentum60.</p>
<section id="data-and-dynamic-graph-construction" class="level3">
<h3 class="anchored" data-anchor-id="data-and-dynamic-graph-construction">Data and dynamic graph construction</h3>
<p>At each monthly rebalance date <span class="math inline">\(t\)</span>, the investable set is reconstructed from active S&amp;P 500 constituents. Stocks are identified by CRSP PERMNO rather than ticker, avoiding look-ahead from ticker changes and share-class reuse. The universe size stays close to 500 names throughout the sample, with minor variation from entries, deletions, and share-class mechanics:</p>
<p><img src="fig1_universe_size.png" class="img-fluid" style="width:100.0%"></p>
<p>Each stock’s node feature vector contains six price-volume signals known at date <span class="math inline">\(t\)</span>:</p>
<p><span class="math display">\[
x_{i,t} = [\text{Mom}_{20},\, \text{Mom}_{60},\, \text{Vol}_{20},\, \text{Vol}_{60},\, \Delta\text{Volume}_{20},\, \beta_{\text{MKT},60}].
\]</span></p>
<p>Momentum is computed from adjusted prices, volatility is the rolling standard deviation of daily returns, volume change captures short-run trading attention, and beta is estimated against an equal-weight market proxy in a leave-one-out style so that a stock’s own return does not mechanically enter its benchmark. All signals are standardized cross-sectionally at each rebalance date. The prediction target is the next-20-trading-day forward return with a one-day execution lag:</p>
<p><span class="math display">\[
y_{i,t} = \frac{P_{i,t+21}}{P_{i,t+1}} - 1.
\]</span></p>
<p>The one-day lag avoids using the signal-date close as both the information set and the execution price. At each rebalance date, the correlation graph <span class="math inline">\(G_t = (V_t, E_t, A_t)\)</span> is rebuilt from the most recent 60 daily returns. Each stock keeps its top <span class="math inline">\(k = 10\)</span> positively correlated neighbors:</p>
<p><span class="math display">\[
A_{ij,t} = \begin{cases} \rho_{ij,t}^{(60)}, &amp; j \in \text{TopK}_{10}^+(i,t), \\ 0, &amp; \text{otherwise.} \end{cases}
\]</span></p>
<p>The graph is therefore sparse, dynamic, and entirely data-driven — it captures changing market relationships (sector rotation, crowding, macro regime) rather than a fixed industry taxonomy.</p>
</section>
<section id="gnn-message-passing-models" class="level3">
<h3 class="anchored" data-anchor-id="gnn-message-passing-models">GNN message-passing models</h3>
<p>Four GNN architectures are evaluated as direct portfolio models. Let <span class="math inline">\(H_t^{(0)} = X_t \in \mathbb{R}^{N_t \times F}\)</span> be the node feature matrix and <span class="math inline">\(G_t\)</span> the dynamic stock graph. Each model outputs one score per stock used for cross-sectional ranking.</p>
<p><strong>GCN</strong> adds self-loops <span class="math inline">\(\tilde{A} = A + I\)</span> and normalizes by degree <span class="math inline">\(\tilde{D}_{ii} = \sum_j \tilde{A}_{ij}\)</span>:</p>
<p><span class="math display">\[
H^{(\ell+1)} = \phi\!\left(\tilde{D}^{-1/2}\tilde{A}\tilde{D}^{-1/2}H^{(\ell)}W^{(\ell)}\right).
\]</span></p>
<p>GCN performs conservative neighborhood smoothing, which is valuable in a low signal-to-noise environment: noisy individual stock labels are averaged over correlated neighbors that share sector, style, or macro exposures, reducing variance at the cost of some per-stock expressiveness.</p>
<p><strong>GraphSAGE</strong> separates a stock’s own representation from an aggregated neighbor mean, making it naturally suited to a dynamic universe where the node set changes every month:</p>
<p><span class="math display">\[
m_i^{(\ell)} = \frac{1}{|\mathcal{N}(i)|}\sum_{j \in \mathcal{N}(i)} h_j^{(\ell)}, \qquad h_i^{(\ell+1)} = \phi(W_s h_i^{(\ell)} + W_n m_i^{(\ell)}).
\]</span></p>
<p><strong>GAT</strong> learns neighbor-specific attention weights from feature similarities, allowing the model to up-weight the most informative neighbors. It is more expressive than GCN but carries higher estimation risk from noisy monthly labels.</p>
<p><strong>APPNP</strong> decouples feature transformation from graph propagation: it first computes an MLP seed <span class="math inline">\(Z = f_\theta(X)\)</span>, then performs personalized PageRank-style diffusion <span class="math inline">\(H^{(r+1)} = (1-\alpha)\hat{A}H^{(r)} + \alpha Z\)</span>. The teleport term <span class="math inline">\(\alpha Z\)</span> prevents excessive drift from the per-stock signal.</p>
<p>All four architectures are trained with a pairwise ranking loss <span class="math inline">\(\mathcal{L} = \frac{1}{|\mathcal{P}|}\sum_{(i,j)\in\mathcal{P}}\log(1 + \exp[-s_{ij}(\hat{y}_{i,t} - \hat{y}_{j,t})])\)</span> where <span class="math inline">\(s_{ij} = \text{sign}(y_{i,t} - y_{j,t})\)</span>. Validation uses cross-sectional rank IC (Spearman correlation between predicted scores and realized forward returns).</p>
</section>
<section id="walk-forward-backtest-protocol" class="level3">
<h3 class="anchored" data-anchor-id="walk-forward-backtest-protocol">Walk-forward backtest protocol</h3>
<p>The backtest uses yearly walk-forward retraining. For test year <span class="math inline">\(Y\)</span>, models train on historical snapshots through <span class="math inline">\(Y-2\)</span>, validate on <span class="math inline">\(Y-1\)</span>, and test on <span class="math inline">\(Y\)</span>. This prevents using future validation information to choose a model for an earlier test year. Monthly returns are non-overlapping: the portfolio enters one trading day after the signal date and exits at the next rebalance entry date. All model-based strategies hold long-only top 20 stocks, equal-weight, with 10 bps transaction cost per unit of absolute turnover. EqualWeight holds all 500 active constituents; Momentum60 ranks by 60-day past return and also takes the top 20. The validation IC traces by test year show modest but consistent signals for GCN and GraphSAGE, with a notable dip around 2021 — the post-COVID regime shift — across all architectures:</p>
<p><img src="fig2_validation_ic.png" class="img-fluid" style="width:100.0%"></p>
</section>
<section id="stage-1-direct-gnn-portfolio-models" class="level3">
<h3 class="anchored" data-anchor-id="stage-1-direct-gnn-portfolio-models">Stage 1: direct GNN portfolio models</h3>
<p>The first experiment asks whether GNNs alone are reliable enough as portfolio managers. The answer is mixed:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Strategy</th>
<th>Ann. Return</th>
<th>Ann. Vol.</th>
<th>Sharpe</th>
<th>Max DD</th>
<th>Turnover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GCN</td>
<td>10.31%</td>
<td>18.99%</td>
<td>0.543</td>
<td>-26.54%</td>
<td>1.64</td>
</tr>
<tr class="even">
<td>GraphSAGE</td>
<td>10.14%</td>
<td>17.16%</td>
<td>0.591</td>
<td>-29.56%</td>
<td>1.66</td>
</tr>
<tr class="odd">
<td>GAT</td>
<td>7.65%</td>
<td>18.59%</td>
<td>0.411</td>
<td>-28.62%</td>
<td>1.60</td>
</tr>
<tr class="even">
<td>APPNP</td>
<td>4.95%</td>
<td>24.19%</td>
<td>0.204</td>
<td>-43.88%</td>
<td>1.61</td>
</tr>
<tr class="odd">
<td>EqualWeight</td>
<td>10.66%</td>
<td>18.06%</td>
<td>0.590</td>
<td>-31.48%</td>
<td>0.02</td>
</tr>
<tr class="even">
<td>Momentum60</td>
<td>5.50%</td>
<td>20.14%</td>
<td>0.273</td>
<td>-34.10%</td>
<td>1.29</td>
</tr>
</tbody>
</table>
<p>GCN and GraphSAGE produce positive OOS Sharpe ratios and competitive returns, but neither clearly dominates EqualWeight — GraphSAGE matches its Sharpe at 0.591 vs 0.590 while running 1.66 monthly turnover versus EqualWeight’s near-zero 0.02. GAT is weaker, and APPNP collapses to a Sharpe of 0.204 and a -43.88% maximum drawdown. The cumulative return chart makes the instability concrete: APPNP’s 2020 drawdown is severe enough to permanently impair the strategy’s trajectory:</p>
<p><img src="fig3_stage1_cumret.png" class="img-fluid" style="width:100.0%"></p>
<p>Adding 10 more features (medium- and long-term momentum, downside volatility, idiosyncratic volatility, a 126-day beta, and volume surge) does not fix the problem. GCN deteriorates sharply to 0.193 Sharpe; GraphSAGE also falls; only GAT improves slightly. The “more features solves it” hypothesis does not hold here. The Stage 1 conclusion is that direct GNN scores are architecture-sensitive, subject to high turnover, and not reliable enough as a standalone portfolio engine. This motivates a role change: use GNNs to create relational representations, then let a tabular model perform the final ranking.</p>
</section>
<section id="stage-2-gcn-as-a-feature-extractor-for-random-forest" class="level3">
<h3 class="anchored" data-anchor-id="stage-2-gcn-as-a-feature-extractor-for-random-forest">Stage 2: GCN as a feature extractor for Random Forest</h3>
<p>Stage 2 keeps the GCN but changes what it delivers. After training, the GCN produces two outputs per stock at each rebalance: a scalar ranking score <span class="math inline">\(\hat{y}_{i,t}^{\text{GCN}}\)</span> and a 64-dimensional hidden embedding <span class="math inline">\(h_{i,t}^{\text{GCN}}\)</span>. These are concatenated with the original six stock features to form an augmented input:</p>
<p><span class="math display">\[
z_{i,t} = \left[x_{i,t} \,\|\, \hat{y}_{i,t}^{\text{GCN}} \,\|\, h_{i,t}^{\text{GCN}}\right], \qquad \hat{s}_{i,t}^{\text{RF}} = f_{\text{RF}}(z_{i,t}).
\]</span></p>
<p>The RF target is the within-month rank transform of realized forward returns, <span class="math inline">\(q_{i,t} = \text{rank}_{i \in V_t}(y_{i,t})/N_t - 0.5\)</span>, which matches the ranking objective without requiring calibrated return forecasts. RF handles nonlinear feature interactions and threshold effects that a GCN’s linear message-passing cannot model; the GCN contributes a denoised, graph-smoothed summary of each stock’s relational context.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Strategy</th>
<th>Ann. Return</th>
<th>Ann. Vol.</th>
<th>Sharpe</th>
<th>Max DD</th>
<th>Turnover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RF Base</td>
<td>8.97%</td>
<td>18.87%</td>
<td>0.475</td>
<td>-29.79%</td>
<td>1.69</td>
</tr>
<tr class="even">
<td>RF + GCN Features</td>
<td>10.07%</td>
<td>18.10%</td>
<td>0.557</td>
<td>-26.32%</td>
<td>1.61</td>
</tr>
<tr class="odd">
<td>GCN Direct</td>
<td>10.31%</td>
<td>18.99%</td>
<td>0.543</td>
<td>-26.54%</td>
<td>1.64</td>
</tr>
<tr class="even">
<td>EqualWeight</td>
<td>10.66%</td>
<td>18.06%</td>
<td>0.590</td>
<td>-31.48%</td>
<td>0.02</td>
</tr>
<tr class="odd">
<td>Momentum60</td>
<td>5.50%</td>
<td>20.14%</td>
<td>0.273</td>
<td>-34.10%</td>
<td>1.29</td>
</tr>
</tbody>
</table>
<p>RF + GCN Features raises Sharpe from 0.475 to 0.557 — a +0.082 lift — and reduces maximum drawdown by 3.47 percentage points relative to RF Base. In the expanded 10-feature setting, the RF standalone reaches only Sharpe 0.370, while RF + GCN Features reaches 0.606, reinforcing the interpretation that the extra tabular features introduce noise when used independently but that GCN graph-smoothing can partially denoise and contextualize them. Nevertheless, the 10-feature final strategy does not beat the 6-feature final strategy, so the project keeps the original six features for robustness and interpretability:</p>
<p><img src="fig4_stage2_cumret.png" class="img-fluid" style="width:100.0%"></p>
</section>
<section id="stage-3-frozen-rf-gcn-final-strategy" class="level3">
<h3 class="anchored" data-anchor-id="stage-3-frozen-rf-gcn-final-strategy">Stage 3: frozen RF + GCN final strategy</h3>
<p>The final strategy is deliberately frozen before OOS evaluation. The pipeline is fixed as: six original features → GCN score and 64-dimensional embeddings → five-seed RF ensemble → long-only equal-weight top 20 selection → 10 bps transaction costs. The five-seed ensemble averages RF predictions across five random draws, reducing sensitivity to a single bootstrap sample:</p>
<p><span class="math display">\[
\hat{s}_{i,t}^{\text{ens}} = \frac{1}{M}\sum_{m=1}^{M} \hat{s}_{i,t}^{(m)}, \qquad M = 5.
\]</span></p>
<p>Freezing means no annual hyperparameter selection, no monthly rule switching, and no after-the-fact model choice across the OOS period. Three implementation variants were also tested (EqualTop20, BufferTop20 with a 30-name holding buffer, and VolTop20 with inverse-volatility weights) but none of them improved the return-risk trade-off enough to replace the seed-ensemble design.</p>
<p><img src="fig5_final_cumret.png" class="img-fluid" style="width:100.0%"></p>
<p>The final strategy achieves 12.33% annualized return, 0.676 Sharpe, and -24.99% maximum drawdown — improvements of +1.89 pp return, +0.105 Sharpe, and +4.26 pp on maximum drawdown relative to RF Base. GCN-derived variables are prominent in the RF’s feature importance: <code>gcn_score</code> is the single most important input (mean impurity importance 0.07), followed by <code>gcn_emb_51</code>, <code>beta_mkt_60</code>, <code>gcn_emb_35</code>, and <code>vol_60</code>. Multiple GCN embedding dimensions rank alongside traditional price-volume signals, supporting the interpretation that the graph representation adds information not already contained in momentum, volatility, and beta alone:</p>
<p><img src="fig6_feature_importance.png" class="img-fluid" style="width:100.0%"></p>
</section>
<section id="limits" class="level3">
<h3 class="anchored" data-anchor-id="limits">Limits</h3>
<p>Several important caveats apply. The OOS period covers 119 monthly rebalances, which is useful but still one historical path: the confidence intervals on Sharpe ratio differences at this sample size are wide, and the outperformance relative to EqualWeight at 10 bps transaction costs becomes fragile at 20 bps — RF + GCN Final falls to Sharpe 0.560 while EqualWeight barely moves to 0.589. The active strategy runs average monthly turnover of 1.60 versus EqualWeight’s near-zero turnover, so implementation costs matter more than they appear in a headline Sharpe comparison.</p>
<p>The graph structure itself is limited to rolling pairwise correlations. Sector classifications, fundamentals, macro variables, and options information are all excluded; the correlation edges can change rapidly across regimes, and expressive attention mechanisms like GAT may overfit short-lived co-movement patterns rather than structural dependencies. Market impact, borrow constraints, and shorting costs are not modeled — the strategy is long-only, but its portfolio concentration (top 20 names) and turnover rate would generate non-trivial impact costs in live trading that the 10 bps flat-rate assumption does not capture.</p>
<p>Finally, EqualWeight is a genuinely hard benchmark because it has near-zero turnover and broad market exposure. The RF + GCN strategy improves Sharpe and maximum drawdown relative to it, but the cost-adjusted return advantage over a simple buy-and-hold of the S&amp;P 500 equal-weight index is modest enough that the project is best read as academic evidence for graph-aware representation value rather than a production-ready trading system.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>