---
title: "Random boxes"
description: " "
order: 12
---

We have 100 people each assigned a box. Create a strategy where each person can open 50 boxes that has at least 30 % chance of success.


::: {.callout-tip collapse="true"}
## 💡 Hint

A permutation can always be decomposed into a product of disjoint cycles.
:::

::: {.callout-tip collapse="true"}
## 💡 Solution

If the strategy was full random, each person would have a chance of 1/2 to find his box. Therefore, the probability of the success is $(1/2)^{100} <<1.$

Let's assume that each person has a number between 1 and 100, the boxes have a number written on them and a number inside them. The goal is that each person has the box with their number inside. Let's start by giving them the box with their number outside. Then, if the number inside is not their, they would pick the box with this given number on the outside. Mathematically, we have a permutation $\sigma()$ and for each person that does not have its number we will compute $\sigma^2()$.

`If after 50 iterations, the person i has not his box, that means that the permutation countains one cycle of length 51 or more` (it is at least one but since the length is higher that the have, it is only one). Accordingly, $\mathbb{P}(\text{success}) = 1 - \sum_{k=51}^{100} \mathbb{P}(\text{cycle length k})$.

Now, in order to compute a cycle of length k, we need to choose the k elements that are in the cycle, then a permutation of the remaining numbers. However, many permutations represent the same cycle (1 for each position of one element). Indeed, the permutations (1, 2, 3), (2, 3, 1), (3, 1, 2) represent the same cycle so we need to divide the number of permutations of the k elements by k. Thus $\mathbb{P}(\text{cycle length k}) =  \binom{n}{k}*\frac{k!}{k}*(n-k)! / n!= 1/k$,

Finally, we get $\boxed{\mathbb{P}(\text{success}) = 1 - \sum_{k=51}^{100} 1/k \approx 1 - (ln(100)-ln(50)) = 1 -ln(2) \approx 0.31.}$
:::

