---
title: "Polya's urn"
description: " "
order: 9
---

An urn initially contains `b white` balls and `r red` balls. The following experiment is carried out:
* A ball is drawn from the urn at random, and its color is noted.
* The ball is returned to the urn, and `d balls of the same color` are added.
The experiment is repeated as many times as desired.
Let $n \ge 1$. Determine the `probability that the ball drawn will be white on the nth draw.`

::: {.callout-tip collapse="true"}
## 💡 Hint

Compute the probability for the first draw, the second, the third. Then make a guess for the general formula and prove it by induction.
:::

::: {.callout-tip collapse="true"}
## 💡 Solution

We denote by $W_n$ the event the a white ball is drew from the nth draw.
Let $P_n : \mathbb{P}(W_n)=\frac{b}{b+r}$

* Initialisation : for $n=1$, there are $b$ white balls among the $b+r$ total balls so the formula is correct at the step 1

* Heredity: Let $n \ge 1$. Assume that the result is true for $n \ge 1$.We cannot use $\mathbb{P}(W_{n+1}  | W_n)$ in our calculations, because we do not know exactly how many balls are in the urn when $W_n$ is true. Except for $W_1$. After one draw, if $W_1$ is true, we have $ b + d $ white balls  and $ r$ red balls. To reach $n + 1$ draws, there remain $n$ draws to perform. This is exactly equivalent to performing $n$ draws starting with $b_0 = b + d$ white balls and $r_0 = r$ red balls. Thus, by the induction hypothesis, we deduce: $\mathbb{P}(W_{n+1} | W_1) = \frac{b_0}{b_0 + r_0} = \frac{b + d}{b + d + r}$. Likewise, in the other case, we have $\mathbb{P}(W_{n+1} | \bar{W_1}) = \frac{b}{b + d + r}.$ Accordingly, $\mathbb{P}(W_{n+1}) = \mathbb{P}(W_{n+1} \mid W_1)\mathbb{P}(W_1) + \mathbb{P}(W_{n+1} \mid \bar{W_1})\mathbb{P}(\bar{W_1})] = \frac{b + d}{b + d + r} \times \frac{b}{b + r} + \frac{b}{b + d + r} \times \frac{r}{b + r}.$ Finally, $\mathbb{P}(W_{n+1})=\frac{b}{b+r}$

By the principle of the induction proof, $\boxed{\forall n \in \mathbb{N}^*, \mathbb{P}(W_n)=\frac{b}{b+r}}$
:::